name: projet_ressources
services:
  db:
    image: postgres:15
    container_name: ressources_relationnelles_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_ressources
    ports:
      - "5433:5432"